# The chain of application is mask > add > delete
# The tags are case sensitive. They should match the DICOM standard dictionary specification
# Mask and delete only work with the tags already present in the dicom file

# Tags are case sensitive. Need to follow the DICOM Stadndard dictionary
# Unique ID to match on, PatientID or PatientName tags suggested. It will defaulted to PatientID
[matchid]
tag = "PatientID"

# List of tags that will be masked by the DeID
[mask]
tags = ["PatientID", "PatientName"]

# List of tags that will be deleted
[delete]
tags = []
private_tags = false

# Dictionary of tags to be added along with their values
[add]
tags.PatientIdentityRemoved = "YES"
tags.DeidentificationMethod = "DCMRig"
